EMPIRIC_FRESHNESS_THRESHOLD = 30 * 60  # 30 minutes
EMPIRIC_SOURCES_THRESHOLD = 3
EMPIRIC_UPDATE_INTERVAL = 10 * 60  # 10 minutes

EMPIRIC_LOWER_FRESHNESS_BOUND = 60
EMPIRIC_UPPER_FRESHNESS_BOUND = 60 * 60 * 4 + 1
EMPIRIC_LOWER_SOURCES_BOUND = 1
EMPIRIC_UPPER_SOURCES_BOUND = 13
EMPIRIC_LOWER_UPDATE_INTERVAL_BOUND = 15
EMPIRIC_UPPER_UPDATE_INTERVAL_BOUND = 60 * 60 * 4 + 1
