from decimal import Decimal

from tests.utils import RAY_SCALE, str_to_felt

BENEFICIARY_REGISTRAR_OWNER = str_to_felt("beneficiary registrar")

BENEFICIARY_1 = str_to_felt("beneficiary 1")
BENEFICIARY_2 = str_to_felt("beneficiary 2")
BENEFICIARY_3 = str_to_felt("beneficiary 3")
BENEFICIARY_4 = str_to_felt("beneficiary 4")
BENEFICIARY_5 = str_to_felt("beneficiary 5")

BENEFICIARY_1_PERCENTAGE = Decimal("0.4")
BENEFICIARY_2_PERCENTAGE = Decimal("0.6")
BENEFICIARY_3_PERCENTAGE = Decimal("0.2")
BENEFICIARY_4_PERCENTAGE = Decimal("0.35")
BENEFICIARY_5_PERCENTAGE = Decimal("0.45")

INITIAL_BENEFICIARIES = [BENEFICIARY_1, BENEFICIARY_2]
INITIAL_PERCENTAGES = [BENEFICIARY_1_PERCENTAGE, BENEFICIARY_2_PERCENTAGE]
INITIAL_PERCENTAGES_RAY = [int(i * RAY_SCALE) for i in INITIAL_PERCENTAGES]

SUBSEQUENT_BENEFICIARIES = [BENEFICIARY_3, BENEFICIARY_4, BENEFICIARY_5]
SUBSEQUENT_PERCENTAGES = [BENEFICIARY_3_PERCENTAGE, BENEFICIARY_4_PERCENTAGE, BENEFICIARY_5_PERCENTAGE]
SUBSEQUENT_PERCENTAGES_RAY = [int(i * RAY_SCALE) for i in SUBSEQUENT_PERCENTAGES]
