from decimal import Decimal

from tests.utils import RAY_SCALE, str_to_felt, to_wad

HARMONIZER_OWNER = str_to_felt("harmonizer owner")

RECIPIENT_1 = str_to_felt("recipient 1")
RECIPIENT_2 = str_to_felt("recipient 2")
RECIPIENT_3 = str_to_felt("recipient 3")
RECIPIENT_4 = str_to_felt("recipient 4")
RECIPIENT_5 = str_to_felt("recipient 5")

RECIPIENT_1_PERCENTAGE = Decimal("0.4")
RECIPIENT_2_PERCENTAGE = Decimal("0.6")
RECIPIENT_3_PERCENTAGE = Decimal("0.2")
RECIPIENT_4_PERCENTAGE = Decimal("0.35")
RECIPIENT_5_PERCENTAGE = Decimal("0.45")

INITIAL_RECIPIENTS = [RECIPIENT_1, RECIPIENT_2]
INITIAL_PERCENTAGES = [RECIPIENT_1_PERCENTAGE, RECIPIENT_2_PERCENTAGE]
INITIAL_PERCENTAGES_RAY = [int(i * RAY_SCALE) for i in INITIAL_PERCENTAGES]

SUBSEQUENT_RECIPIENTS = [RECIPIENT_3, RECIPIENT_4, RECIPIENT_5]
SUBSEQUENT_PERCENTAGES = [RECIPIENT_3_PERCENTAGE, RECIPIENT_4_PERCENTAGE, RECIPIENT_5_PERCENTAGE]
SUBSEQUENT_PERCENTAGES_RAY = [int(i * RAY_SCALE) for i in SUBSEQUENT_PERCENTAGES]

DEBT_INCREMENT = Decimal("10_000")
DEBT_INCREMENT_WAD = to_wad(DEBT_INCREMENT)
