from tests.utils import WBTC_DECIMALS, str_to_felt, to_fixed_point, to_wad

#
# users
#


OTHER_USER = str_to_felt("other user")


#
# module consts
#

INITIAL_STETH_DEPOSIT = to_wad(20)
INITIAL_DOGE_DEPOSIT = to_wad(1000)
INITIAL_WBTC_AMT = 5
INITIAL_WBTC_DEPOSIT = to_fixed_point(INITIAL_WBTC_AMT, WBTC_DECIMALS)
INITIAL_WBTC_YANG = to_wad(INITIAL_WBTC_AMT)
INITIAL_DEPOSITS = (INITIAL_STETH_DEPOSIT, INITIAL_DOGE_DEPOSIT, INITIAL_WBTC_DEPOSIT)
INITIAL_YANG_AMTS = (INITIAL_STETH_DEPOSIT, INITIAL_DOGE_DEPOSIT, INITIAL_WBTC_YANG)

INITIAL_FORGED_AMOUNT = to_wad(4000)

SUBSEQUENT_STETH_DEPOSIT = to_wad(1)
SUBSEQUENT_DOGE_DEPOSIT = to_wad(200)
SUBSEQUENT_WBTC_AMT = 1
SUBSEQUENT_WBTC_DEPOSIT = to_fixed_point(SUBSEQUENT_WBTC_AMT, WBTC_DECIMALS)
SUBSEQUENT_WBTC_YANG = to_wad(SUBSEQUENT_WBTC_AMT)
SUBSEQUENT_DEPOSITS = (SUBSEQUENT_STETH_DEPOSIT, SUBSEQUENT_DOGE_DEPOSIT, SUBSEQUENT_WBTC_DEPOSIT)
SUBSEQUENT_YANG_AMTS = (SUBSEQUENT_STETH_DEPOSIT, SUBSEQUENT_DOGE_DEPOSIT, SUBSEQUENT_WBTC_YANG)

STETH_WITHDRAW_AMT = to_wad(2)
DOGE_WITHDRAW_AMT = to_wad(50)
WBTC_WITHDRAW = 1
WBTC_WITHDRAW_AMT = to_fixed_point(WBTC_WITHDRAW, WBTC_DECIMALS)
WBTC_WITHDRAW_YANG_AMT = to_wad(WBTC_WITHDRAW)
WITHDRAW_AMTS = (STETH_WITHDRAW_AMT, DOGE_WITHDRAW_AMT, WBTC_WITHDRAW_AMT)
WITHDRAW_YANG_AMTS = (STETH_WITHDRAW_AMT, DOGE_WITHDRAW_AMT, WBTC_WITHDRAW_YANG_AMT)
