from decimal import Decimal

from tests.utils import RAY_PERCENT, str_to_felt, to_wad

EQUALIZER_OWNER = str_to_felt("equalizer owner")

RECIPIENT_1 = str_to_felt("recipient 1")
RECIPIENT_2 = str_to_felt("recipient 2")
RECIPIENT_3 = str_to_felt("recipient 3")
RECIPIENT_4 = str_to_felt("recipient 4")
RECIPIENT_5 = str_to_felt("recipient 5")

# Initial set of recipients
RECIPIENT_1_PERCENTAGE = 40 * RAY_PERCENT
RECIPIENT_2_PERCENTAGE = 60 * RAY_PERCENT

INITIAL_RECIPIENTS = [RECIPIENT_1, RECIPIENT_2]
INITIAL_PERCENTAGES_RAY = [RECIPIENT_1_PERCENTAGE, RECIPIENT_2_PERCENTAGE]

# Subsequent set of recipients
RECIPIENT_3_PERCENTAGE = 20 * RAY_PERCENT
RECIPIENT_4_PERCENTAGE = 35 * RAY_PERCENT
RECIPIENT_5_PERCENTAGE = 45 * RAY_PERCENT

SUBSEQUENT_RECIPIENTS = [RECIPIENT_3, RECIPIENT_4, RECIPIENT_5]
SUBSEQUENT_PERCENTAGES_RAY = [RECIPIENT_3_PERCENTAGE, RECIPIENT_4_PERCENTAGE, RECIPIENT_5_PERCENTAGE]

DEBT_INCREMENT = Decimal("10_000")
DEBT_INCREMENT_WAD = to_wad(DEBT_INCREMENT)
