name: Amarna Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: pip
          cache-dependency-path: '**/requirements-dev.txt'

      - name: Env setup
        run: pip install -r requirements-dev.txt

      - name: Install Amarna
        run: git clone https://github.com/crytic/amarna.git && cd amarna && pip install -e .

      - name: Run Amarna Static Analysis
        run: amarna contracts/ -o out.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: out.sarif