name: Cairo tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"

jobs:
  test:
    if: >-
      !github.event.pull_request.draft &&
      !(contains(toJSON(github.event.commits.*.message), '[skip ci]') ||
        contains(toJSON(github.event.commits.*.message), '[ci skip]'))
    runs-on: cairo-test-eater-64

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: pip
          cache-dependency-path: '**/requirements-dev.txt'

      - name: Install deps
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest -sv -r A tests
