name: Cairo 1.0

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest commit hash
        run: |
          echo "CAIRO_HASH=$( curl -u "u:${{ github.token }}" https://api.github.com/repos/starkware-libs/cairo/git/ref/heads/main | jq .object.sha | tr -d '"' )" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-03

      - name: Cache setup
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            **/target
          key: ${{ runner.os }}-cargo-${{ env.CAIRO_HASH }}

      - name: Env setup
        run: make build

      - name: Lint Cairo 1.x code
        run: make check-format

      - name: Compile Cairo 1.x code
        run:
          find contracts-1.0 -type f -name '*.cairo' |
          xargs -n1 cargo run --manifest-path=./cairo/Cargo.toml --bin starknet-compile > /dev/null
