name: Cairo 1.0

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"

env:
  CAIRO_INSTALLATION_FOLDER: ./cairo
  SCARB_INSTALLATION_FOLDER: ./scarb

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest commit hash
        run: |
          echo "CAIRO_HASH=$( curl -u "u:${{ github.token }}" https://api.github.com/repos/starkware-libs/cairo/git/ref/heads/main | jq .object.sha | tr -d '"' )" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-03

      - name: Get cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            **/target
            ~/.cairo
            ~/.scarb
          key: ${{ runner.os }}-cargo-${{ env.CAIRO_HASH }}
          restore-keys: Linux-cargo-

      - name: Pull dependencies
        run: |
          if [ -d $SCARB_INSTALLATION_FOLDER ]; then \
            git -C $SCARB_INSTALLATION_FOLDER pull; \
          else \
            git clone --depth 1 https://github.com/software-mansion/scarb.git $SCARB_INSTALLATION_FOLDER; \
          fi
          if [ -d $CAIRO_INSTALLATION_FOLDER ]; then
            git -C $CAIRO_INSTALLATION_FOLDER pull; \
          else \
            git clone --depth 1 https://github.com/starkware-libs/cairo.git $CAIRO_INSTALLATION_FOLDER; \
          fi

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cargo build --manifest-path=./scarb/Cargo.toml
          cargo build --manifest-path=./cairo/Cargo.toml

      - uses: actions/cache/save@v3
        if: always()
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            **/target
            ~/.cairo
            ~/.scarb
          key: ${{ runner.os }}-cargo-${{ env.CAIRO_HASH }}

      - name: Add Scarb to PATH
        run: echo "$SCARB_INSTALLATION_FOLDER/target/debug" >> $GITHUB_PATH

      - name: Lint Cairo 1.x code
        run: scarb fmt --check --verbose

      - name: Add Cairo to PATH
        run: echo "$CAIRO_INSTALLATION_FOLDER/target/debug" >> $GITHUB_PATH

      - name: Test Cairo 1.x code in Cairo
        run: scarb run test
