name: Cairo tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test:
    if: >-
      !github.event.pull_request.draft &&
      !(contains(toJSON(github.event.commits.*.message), '[skip ci]') ||
        contains(toJSON(github.event.commits.*.message), '[ci skip]'))
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update PATH
        run: echo "/home/ec2-user/.local/bin:/usr/local/bin" >> $GITHUB_PATH

      - name: Install deps
        run: pip3.9 install -r requirements-dev.txt

      - name: Run tests
        run: pytest -sv -r A tests
