name: Lint

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-11-03

      - name: Python setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: pip
          cache-dependency-path: '**/requirements-dev.txt'

      - name: Env setup
        run: pip install -r requirements-dev.txt | make install

      - name: Lint Cairo 0.x code
        run: find contracts -type f -name '*.cairo' | xargs cairo-format -c

      - name: Lint Cairo 1.x code
        run: make check-format

      - name: Run black
        run: black --line-length=120 --check .

      - name: Run flake8
        run: flake8

      - name: Run isort
        run: isort --check-only --diff tests/
