name: Python dependencies

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"

jobs:
  pip-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: pip
          cache-dependency-path: '**/requirements-dev.txt'

      - name: Env setup
        run: pip install -r requirements-dev.txt

      - name: Install pip-audit
        run: pip install git+https://github.com/pypa/pip-audit.git@5775f9e4416465b43e5667874444fe4728d149dd

      - name: Run pip-audit
        run: pip-audit -r requirements-dev.txt --ignore-vuln PYSEC-2021-427
