name: Python dependencies

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"

jobs:
  pip-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run pip-audit
        uses: pypa/gh-action-pip-audit@v1.0.4
        with:
          inputs: requirements-dev.txt
          ignore-vulns: PYSEC-2021-427
          internal-be-careful-debug: true
