name: Python dependencies

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: |
          python -m venv env/
          source env/bin/activate
          python -m pip install -r requirements-dev.txt
          python -m pip uninstall pkg_resources
      - uses: trailofbits/gh-action-pip-audit@v0.0.5
        with:
          virtual-environment: env/
          local: true
          inputs: requirements-dev.txt
