[sncast.devnet]
account = "devnet_admin"
accounts-file = "../devnet_accounts.json"
url = "http://127.0.0.1:5050"

[sncast.mainnet]
account = "../mainnet_admin.json"
keystore = "../mainnet_admin_keystore.json"
url = "https://free-rpc.nethermind.io/mainnet-juno"

[sncast.sepolia]
account = "../sepolia_admin.json"
keystore = "../sepolia_admin_keystore.json"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
